version: "3"

networks:
    application:
        driver: bridge
volumes:
    storage:
        driver: local

services:
    app:    
        build: 
            context: docker/
            args:
                TIMEZONE: ${TIMEZONE}    
        container_name: app
        depends_on:
          - localstack
        environment:
          - AWS_ACCESS_KEY_ID=localkey
          - AWS_SECRET_ACCESS_KEY=localsecret
        ports:
            - 80:8080
        expose:
            - "9000"
            - "9001"      
        volumes:
            - .:/home/php/app
        networks:
            - application
    localstack:
        image: localstack/localstack:latest
        container_name: localstack_demo
        ports:
          - '4567-4599:4567-4599'
          - '8080:8080'
        environment:
          - SERVICES=s3, sqs, sns, dynamodb 
          - DEBUG=1
          - DATA_DIR=/tmp/localstack/data
        volumes:
          - './../autodockerwin/.localstack:/tmp/localstack'
          - '/var/run/docker.sock:/var/run/docker.sock' 